SET(CUE_INCLUDE_DIR /usr/include/libcue-1.4/libcue)

FIND_LIBRARY(CUE_LIBRARIES NAMES cue)

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(Cue REQUIRED_VARS CUE_LIBRARIES CUE_INCLUDE_DIR)

MARK_AS_ADVANCED(CUE_INCLUDE_DIR CUE_LIBRARIES)
